### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by tranpqvu** [mdutt247/laravel-news#6]
The first thank for your source code.
 I need to set privilege for post, example some post is seen only with user have pay for content.
 How can i do with your code to do it. 
Thanks a lot.

**Comment by coderbhaai** [comment]
use middleware in it?
The middleware checks if the wallet is recharged and then directs the user accordingly

**Comment by mdutt247** [comment]
Let's first come to your problem - you want to show the content (all posts?) to paid users.

To achieve this you need to "authorize" users after "authentication?".

This can be achieved in many ways - **Policy**/Gate/Middleware etc, you write your own logic or use some ready-made package like spatie/laravel-permission.

As for as this laravel-news is concerned, the admin panel is on the _Web route_ and the user will see the posts on a mobile device - which will consume the _API route_, you need to create a mobile app. A token is created (by Sanctum https://laravel.com/docs/8.x/sanctum) when the user logs into the mobile device you can add "**token abilities**" while creating token. And the single post serving method will show the post or deny the request.

**Comment by mdutt247** [comment]
@tranpqvu the question is answered. I am closing it.

**Comment by tonywtrd** [comment]
Actually, there's no "role" feature in this app as any user can delete post.
